version: '3.1'

services:
  api: 
    image: 'node:14.17.6-alpine'
    working_dir: /app
    env_file:
      - services/api/.env
    entrypoint: 'sh -c "npm install && node_modules/.bin/nodemon"'
    volumes:
      - "./services/api:/app"
    ports:
      - 5000:80

  secondary: 
    image: 'node:14.17.6-alpine'
    working_dir: /app
    env_file:
      - services/secondary/.env
    entrypoint: 'sh -c "npm install && node_modules/.bin/nodemon"'
    volumes:
      - "./services/secondary:/app"
    ports:
      - 5001:80